//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI.addPark {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="addPark.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddPark", ReplyAction="http://tempuri.org/IService1/AddParkResponse")]
        string AddPark(string type, string Owner, string Name, string address, string Url, string NeighboringStates, string Establishedn, string Founder);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddPark", ReplyAction="http://tempuri.org/IService1/AddParkResponse")]
        System.Threading.Tasks.Task<string> AddParkAsync(string type, string Owner, string Name, string address, string Url, string NeighboringStates, string Establishedn, string Founder);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : GUI.addPark.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<GUI.addPark.IService1>, GUI.addPark.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AddPark(string type, string Owner, string Name, string address, string Url, string NeighboringStates, string Establishedn, string Founder) {
            return base.Channel.AddPark(type, Owner, Name, address, Url, NeighboringStates, Establishedn, Founder);
        }
        
        public System.Threading.Tasks.Task<string> AddParkAsync(string type, string Owner, string Name, string address, string Url, string NeighboringStates, string Establishedn, string Founder) {
            return base.Channel.AddParkAsync(type, Owner, Name, address, Url, NeighboringStates, Establishedn, Founder);
        }
    }
}
